name: Manual (uv) Dependency Check

on:
  workflow_dispatch:
    inputs:
      python-version:
        description: 'Python version'
        required: true
        default: '3.12.4'
        type: choice
        options:
        - '3.7'
        - '3.8'
        - '3.9'
        - '3.10'
        - '3.11'
        - '3.12'
        - '3.12.4'

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "0.4.27"
        
    - name: Set up Python
      run: uv python install ${{ github.event.inputs.python-version }}
      
    - name: Install and check dependencies
      run: |
        uv init example -p ${{ github.event.inputs.python-version }}
        cp requirements.txt example/requirements.txt
        cd example
        uv venv
        uv pip install setuptools
        uv pip sync requirements.txt
        uv pip install -r requirements.txt
        uv add pipdeptree
        uv tree
        uv pip freeze

    - name: Save dependency details
      run: |
        # Create a timestamp for the folder name
        TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
        RUN_ID="${TIMESTAMP}_run_${{ github.run_id }}"
        
        # Create the dependencies directory if it doesn't exist
        mkdir -p dependency_reports/$RUN_ID
        
        # Save detailed dependencies to file
        cd example
        uv pip freeze > ../dependency_reports/$RUN_ID/dependencies_py${{ github.event.inputs.python-version }}.txt
        uv tree > ../dependency_reports/$RUN_ID/dependency_tree_py${{ github.event.inputs.python-version }}.txt
        
        # Also save Python version for reference
        echo "Python version: ${{ github.event.inputs.python-version }}" > ../dependency_reports/$RUN_ID/metadata.txt
        echo "Run timestamp: $(date)" >> ../dependency_reports/$RUN_ID/metadata.txt
        echo "Workflow run ID: ${{ github.run_id }}" >> ../dependency_reports/$RUN_ID/metadata.txt
    
    - name: Commit dependency report
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add dependency_reports/
        git commit -m "Add dependency report for Python ${{ github.event.inputs.python-version }} (Run ID: ${{ github.run_id }})" || echo "No changes to commit"
        git push
