name: Manual (uv) Dependency Check
on:
  workflow_dispatch:
    inputs:
      python-version:
        description: 'Python version'
        required: true
        default: '3.12.4'
        type: choice
        options:
        - '3.7'
        - '3.8'
        - '3.9'
        - '3.10'
        - '3.11'
        - '3.12'
        - '3.12.4'
jobs:
  dependency-check:
    runs-on: ubuntu-latest
    # Add permission to allow writing to the repository
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "0.4.27"
    - name: Set up Python
      run: uv python install ${{ github.event.inputs.python-version }}
    
    - name: Create timestamp and directory for reports
      id: setup_dirs
      run: |
        # Create a timestamp for the folder name
        TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
        RUN_ID="${TIMESTAMP}_run_${{ github.run_id }}"
        echo "report_dir=dependency_reports/$RUN_ID" >> $GITHUB_OUTPUT
        
        # Create the dependencies directory
        mkdir -p dependency_reports/$RUN_ID
        
        # Save initial metadata
        echo "Python version: ${{ github.event.inputs.python-version }}" > dependency_reports/$RUN_ID/metadata.txt
        echo "Run timestamp: $(date)" >> dependency_reports/$RUN_ID/metadata.txt
        echo "Workflow run ID: ${{ github.run_id }}" >> dependency_reports/$RUN_ID/metadata.txt
    
    - name: Install and check dependencies
      id: install_deps
      run: |
        uv init example -p ${{ github.event.inputs.python-version }}
        cp requirements.txt example/requirements.txt
        cd example
        uv venv
        uv pip install setuptools
        
        # Run pip sync and capture any errors
        uv pip sync requirements.txt > "../${{ steps.setup_dirs.outputs.report_dir }}/sync_output.txt" 2>&1 || {
          echo "pip sync failed with status $?" >> "../${{ steps.setup_dirs.outputs.report_dir }}/error_log.txt"
          echo "ERROR_OCCURRED=true" >> $GITHUB_OUTPUT
        }
        
        # Run pip install and capture any errors
        uv pip install -r requirements.txt > "../${{ steps.setup_dirs.outputs.report_dir }}/install_output.txt" 2>&1 || {
          echo "pip install failed with status $?" >> "../${{ steps.setup_dirs.outputs.report_dir }}/error_log.txt"
          echo "ERROR_OCCURRED=true" >> $GITHUB_OUTPUT
        }
        
        # Only proceed with these if the installation succeeded
        if [ -z "${ERROR_OCCURRED}" ]; then
          uv add pipdeptree
          uv tree > "../${{ steps.setup_dirs.outputs.report_dir }}/dependency_tree_py${{ github.event.inputs.python-version }}.txt" 2>&1 || {
            echo "uv tree failed with status $?" >> "../${{ steps.setup_dirs.outputs.report_dir }}/error_log.txt"
          }
          uv pip freeze > "../${{ steps.setup_dirs.outputs.report_dir }}/dependencies_py${{ github.event.inputs.python-version }}.txt" 2>&1 || {
            echo "pip freeze failed with status $?" >> "../${{ steps.setup_dirs.outputs.report_dir }}/error_log.txt"
          }
        fi
        
        # Update metadata with status
        if [ -f "../${{ steps.setup_dirs.outputs.report_dir }}/error_log.txt" ]; then
          echo "Status: FAILED" >> "../${{ steps.setup_dirs.outputs.report_dir }}/metadata.txt"
          cat "../${{ steps.setup_dirs.outputs.report_dir }}/error_log.txt" >> "../${{ steps.setup_dirs.outputs.report_dir }}/metadata.txt"
        else
          echo "Status: SUCCESS" >> "../${{ steps.setup_dirs.outputs.report_dir }}/metadata.txt"
        fi
      continue-on-error: true
    
    - name: Commit dependency report
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add dependency_reports/
        
        if [ -f "${{ steps.setup_dirs.outputs.report_dir }}/error_log.txt" ]; then
          git commit -m "Add dependency report for Python ${{ github.event.inputs.python-version }} (Run ID: ${{ github.run_id }}) - FAILED" || echo "No changes to commit"
        else
          git commit -m "Add dependency report for Python ${{ github.event.inputs.python-version }} (Run ID: ${{ github.run_id }}) - SUCCESS" || echo "No changes to commit"
        fi
        
        git push
