name: Manual (uv) Dependency Check

on:
  workflow_dispatch:
    inputs:
      python-version:
        description: 'Python version'
        required: true
        default: '3.11'
        type: choice
        options:
        - '3.7'
        - '3.8'
        - '3.9'
        - '3.10'
        - '3.11'
        - '3.12'

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "0.4.27"
    - name: Set up Python
      run: uv python install ${{ github.event.inputs.python-version }}
    - name: Install and check dependencies
      run: |
        uv init example -p ${{ github.event.inputs.python-version }}
        cd example
        uv venv
        uv pip sync requirements.txt
    - name: Install dependencies and view tree
      run: |
        uv pip install -r requirements.txt
        uv add pipdeptree
        uv pipdeptree
    - name: Run pip freeze
      run: uv pip freeze
    # - name: Run tests
    #   run: |
    #     uv pip install pytest
    #     pytest
