name: Manual (uv) Dependency Check
on:
  workflow_dispatch:
    inputs:
      python-version:
        description: 'Python version'
        required: true
        default: '3.11'
        type: choice
        options:
        - '3.7'
        - '3.8'
        - '3.9'
        - '3.10'
        - '3.11'
        - '3.12'
jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ github.event.inputs.python-version }}
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        uv venv
        uv add pipdeptree
        ls
    - name: Check dependencies
      run: |
        cd venv
        uv pip sync requirements.txt
        uv pipdeptree
    - name: Run pip freeze
      run: uv pip freeze
    # - name: Run tests
    #   run: |
    #     uv pip install pytest
    #     pytest
